# Generated by Django 2.0 on 2019-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_fuelconsumption_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
