# Generated by Django 2.0 on 2019-04-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_auto_20190405_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelConsumption_string',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('brand', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=1)),
                ('km_per_liter_ethanol_city', models.CharField(max_length=4)),
                ('km_per_liter_ethanol_road', models.CharField(max_length=4)),
                ('km_per_liter_gas_city', models.CharField(max_length=4)),
                ('km_per_liter_gas_road', models.CharField(max_length=4)),
            ],
        ),
    ]
