# Generated by Django 2.0 on 2019-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_fuelconsumption_engine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelConsumption_engine',
        ),
        migrations.DeleteModel(
            name='FuelConsumption_motor',
        ),
        migrations.DeleteModel(
            name='FuelConsumption_string',
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='engine',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
