# Generated by Django 2.0 on 2019-04-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0011_fcshort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='year',
            field=models.CharField(max_length=64),
        ),
    ]
