# Generated by Django 2.2 on 2019-05-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0013_auto_20190425_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcshort',
            name='year',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
