# Generated by Django 2.2 on 2019-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0014_auto_20190503_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcshort',
            name='year',
            field=models.CharField(default=0, max_length=191),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='year',
            field=models.CharField(max_length=191),
        ),
    ]
